# -*- coding: utf-8 -*-
"""Supervised_learning-Assignment--Random Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdXaRZ4GwnzTGssnz7PSdacanHtC-8gx
"""

import pandas as pd

import numpy as np

df = pd.read_csv("/content/Energy_consumption.csv")

df.head(2)

df.dtypes

df.info()

df.isnull().sum()

df.head(10)

df.drop('DayOfWeek', axis=1, inplace=True)
display(df.head())

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['Date'] = df['Timestamp'].dt.date
display(df.head())

df['Timestamp'] = df['Timestamp'].dt.time
display(df.head())

df.head()



cols = ['Date'] + [col for col in df.columns if col != 'Date']
df = df[cols]
display(df.head())

df.dtypes

df.loc[:, 'Day'] = pd.to_datetime(df['Date']).dt.day_name()
display(df.head())

cols = df.columns.tolist()
cols.remove('Day')
holiday_idx = cols.index('Holiday')
cols.insert(holiday_idx, 'Day')
df = df[cols]
display(df.head())

# df['total energy consumption'] = df['EnergyConsumption'] - df['RenewableEnergy']
# df.drop('EnergyConsumption', axis=1, inplace=True)
# df.drop('RenewableEnergy', axis=1, inplace=True)
# df = df.rename(columns={"total energy consumption": "EnergyConsumption"})

df['HVACUsage'] = df['HVACUsage'].map({'On':1, 'Off':0})
df['LightingUsage'] = df['LightingUsage'].map({'On':1, 'Off':0})
df['Holiday'] = df['Holiday'].map({'Yes':1, 'No':0})

df.head()



df['SquareFootage'].min()

df['SquareFootage'].max()

df['Hour'] = df['Timestamp'].apply(lambda x: x.hour)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

df['Day'] = df['Day'].astype('category').cat.codes
df['Day']

X = df.drop('EnergyConsumption', axis=1)
y = df['EnergyConsumption']

rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=8,              # restrict tree depth
    min_samples_split=10,     # prevent small splits
    min_samples_leaf=5,       # prevent tiny leaves
    max_features="sqrt",      # reduce correlation
    random_state=42
)

rf.fit(X_train, y_train)


print("Train R2:", rf.score(X_train, y_train))
print("Test R2:", rf.score(X_test, y_test))

y_pred = rf.predict(X_test)

import matplotlib.pyplot as plt

importances = rf.feature_importances_
features = X_train.columns

plt.figure(figsize=(8,5))
plt.barh(features, importances)
plt.xlabel("Importance")
plt.title("Random Forest Feature Importance")
plt.show()

df.drop(columns=['Date', 'Timestamp']).corr()["EnergyConsumption"].sort_values(ascending=False)

import pandas as pd

importance = pd.Series(rf.feature_importances_, index=X_train.columns)
print(importance.sort_values(ascending=False))

print("Train R2:", rf.score(X_train, y_train))
print("Test R2:", rf.score(X_test, y_test))

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

import pickle

import joblib
joblib.dump(rf, "rf_energy_model.pkl")

from google.colab import files
files.download("rf_energy_model.pkl")

print(X_train.columns)

